name: Deploy to testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to testing
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd deploy
          ./run.sh
